### ISSUE TITLE
[Enhancement/Testing] Add C & P states ACPI tables ported from Clover's automatic injection "Generate"

### ISSUE THREAD

**Issue by whatnameisit** [lshbluesky/Samsung-Sens-Q36-Hackintosh#1]
안녕하세요. 내용 읽어보다가 도움이 될지 싶어서 글 남깁니다.
[README의 Issues](https://github.com/lshbluesky/Samsung-Sens-Q36-Hackintosh/blame/master/README.md#L25) 부분에서 [Dortania에서 따오신 것으로 보이는 글 "Does not support P and C state generation for older CPUs"](https://dortania.github.io/OpenCore-Install-Guide/why-oc.html#opencore-s-shortcomings)은 오픈코어는 클로버와 다르게 특별한 경우 외에는 ACPI Table을 별도로 수정하거나 생성하지 않는다는 의미로 이해하시면 됩니다. 클로버의 config.plist ACPI/SSDT/Generate는 컴퓨터의 ACPI를 읽어서 해당 ProcessorObj Scope에 별도 내용을 넣어주는데, 예를 들면 PluginType를 입력한다면 오픈코어의 SSDT-PLUG.aml와 같이 plugin-type=1가 들어간 SSDT를 ACPI에 추가합니다. 다른 옵션들도 마찬가지며, MaciASL에 File/New from ACPI 눌러보시면 추가되거나 수정된 테이블 확인해보실 수 있습니다.
오픈코어는 이 기능이 없고, 클로버에서 쉽게 필요한 부분을 추출할 수 있으므로, MaciASL로 추가/수정된 SSDT를 별도 aml 파일로 저장해서 오픈코어에 필요한 부분을 추가하면 오픈코어에서도 스피드스텝이 작동할 것 같습니다.

참고내용: [[Guide] Native Power Management for Laptops by RehabMan](https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801/)
<details>
Note on older CPUs

For CPUs older than Sandy Bridge, use config.plist/Generate=true instead of custom SSDT.aml. Since that option causes Clover to generate replacement CPU SSDTs, you will also need to drop the OEM CPU related SSDTs. Usually that means setting config.plist/ACPI/SSDT/DropOem=true, although you may be able to drop the individual tables with DropTables.
</details>

**Comment by lshbluesky** [comment]
안녕하세요.
글 남겨주셔서 감사합니다. :)

최근에 Mac OS X Snow Leopard 10.6.8 버전으로 클린 설치를 해서 OS X Lion 10.7.5 버전은 설치되어 있지 않은 상태인데,
RehabMan 님의 최신 버전과 구 버전의 모든 MaciASL 앱이 Mac OS X Snow Leopard 10.6.8 에서 실행이 되지 않습니다... ㅜㅅㅠ
나중에, OS X Lion 10.7.5 설치를 완료하면 MaciASL 로 Clover 가 추가 및 수정한 CPU 관련 SSDT Table 을 추출해 보겠습니다.

그런데, 혹시나 해서 ssdtPRGen 으로 Intel Merom Core 2 Duo T5600 CPU 의 정보를
User Defined.cfg 에 `T5600,34,800,1830,1830,2,2` 로 추가한 후에
`ssdtPRGen.sh -p T5600 -x 0` 으로 CPU PM SSDT 를 생성하여 OC 에 추가하고
`CpuPm, Cpu0Cst, Cpu0Ist, Cpu1Cst, Cpu1Ist` 5개의 OEM SSDT Tables 를 모두 Drop 하고 다시 부팅해보았지만
부팅 로그에서 다음과 같은 로그가 출력되고 Speed Step 이 작동하지 않네요... ㅜㅅㅠ

    ACPI_SMC_PlatformPlugin::pushCPU_CSTData - _CST evaluation failed
    ACPI_SMC_PlatformPlugin::registerLPCDriver - WARNING - LPC device initialization failed: C-state power management not initialized

ssdtPRGen 으로 생성한 SSDT : [SSDT-PM.aml.zip](https://github.com/lshbluesky/Samsung-Sens-Q36-Hackintosh/files/6154451/SSDT-PM.aml.zip)

ssdtPRGen 으로 생성한 SSDT 에서 ACST 와 APSS 를 각각 _CST 와 _PSS 로 Rename 하여도 동일합니다.

OS X Lion 10.7.5 설치를 완료하고 Clover 가 추가 및 수정한 CPU 관련 SSDT Table 추출이 완료되면 추가로 글 작성하겠습니다.
좋은 하루 보내세요. ✨
안녕히 계세요. :)

**Comment by whatnameisit** [comment]
혹시 10.7.5 설치하기 전이라면 클로버 메뉴에서 F5로 Patched DSDT 저장해보세요. 클로버 구버전에서 이 기능이 지원되는지는 잘 모르겠습니다.

**Comment by lshbluesky** [comment]
> 혹시 10.7.5 설치하기 전이라면 클로버 메뉴에서 F5로 Patched DSDT 저장해보세요. 클로버 구버전에서 이 기능이 지원되는지는 잘 모르겠습니다.

Clover r5119 버전으로 USB 를 만들고 Patched 폴더에 수정 및 패치한 DSDT.aml 은 추가하지 않았으며
Config.plist 에서 ACPI - SSDT - Generate Options - Generate CStates & PStates 두 개의 옵션을 모두 True 로 설정하고
클로버 부트로더 화면에서 F5 키를 눌러서 저장한 Patched DSDT 를 첨부합니다.
[DSDT-104400D4.aml.zip](https://github.com/lshbluesky/Samsung-Sens-Q36-Hackintosh/files/6155220/DSDT-104400D4.aml.zip)

그런데, Patched DSDT 를 확인해보니 _PR.CPU0과 _PR.CPU1 의 ProcessorObj 에 아무 값도 들어있지 않네요... ㅜㅅㅠ

Clover r3793 버전은 F1 도움말 화면에서 F5 키를 누르면 Patched DSDT 가 저장된다고 되어 있지만
F5 키를 눌러도 확인해보면 저장되어 있지 않았습니다. -_-

**Comment by whatnameisit** [comment]
F4가 OEM ACPI를 저장하기 때문에 F5는 패치된 ACPI를 저장할 것으로 생각했는데 [DSDT](https://sourceforge.net/p/cloverefiboot/wiki/Fixing-DSDT/)만 저장하네요. 다음은 클로버 소스코드에서 C/Pstate 테이블을 추출하거나 말씀하셨듯이 10.7.5를 설치해서 봐야 하지 않을까 싶습니다. [전자](https://github.com/CloverHackyColor/CloverBootloader/blob/master/rEFIt_UEFI/Platform/StateGenerator.cpp)는 저는 불가능하네요..

**Comment by lshbluesky** [comment]
> F4가 OEM ACPI를 저장하기 때문에 F5는 패치된 ACPI를 저장할 것으로 생각했는데 [DSDT](https://sourceforge.net/p/cloverefiboot/wiki/Fixing-DSDT/)만 저장하네요. 다음은 클로버 소스코드에서 C/Pstate 테이블을 추출하거나 말씀하셨듯이 10.7.5를 설치해서 봐야 하지 않을까 싶습니다. [전자](https://github.com/CloverHackyColor/CloverBootloader/blob/master/rEFIt_UEFI/Platform/StateGenerator.cpp)는 저는 불가능하네요..

OS X Lion 10.7.5 를 설치한 후에 RehabMan 님의 MaciASL 로 Clover 가 추가 및 수정한 CPU 관련 SSDT Table 을 추출하였습니다. :)
SSDT-2,3,4 모두 포함되어 있습니다.
[T5600 CPU SSDT.zip](https://github.com/lshbluesky/Samsung-Sens-Q36-Hackintosh/files/6161029/T5600.CPU.SSDT.zip)

![스크린샷 2021-03-18 오전 11 31 56](https://user-images.githubusercontent.com/61459016/111566096-ef77e180-87df-11eb-8ee6-784466ceecd2.png)

`CpuPm` 이 2개인데 위의 SSDT-2-CpuPm 은 내용을 보니 기존의 OEM ACPI Tables 에 있었던 것 같아요.
Clover 가 `Cpu0Cst, Cpu0Ist, Cpu1Cst, Cpu1Ist` 테이블은 자동으로 Drop 한 것 같습니다.
그리고, 아래에 있는 `CpuPm, CpuCst` 이 Clover 가 추가 및 수정한 CPU 관련 SSDT Tables 인 것 같아요.

OpenCore 에서 `Cpu0Cst, Cpu0Ist, Cpu1Cst, Cpu1Ist` 테이블은 Drop 한 후에 SSDT-3,4 만 추가하고 다시 부팅해볼게요. :)

**Comment by lshbluesky** [comment]
OpenCore 로 `Cpu0Cst, Cpu0Ist, Cpu1Cst, Cpu1Ist` 테이블을 Drop 한 후에
SSDT-3,4 를 추가하고 부팅하였지만 Speed Step 이 작동하지 않습니다... ㅜㅅㅠ
기존의 OEM ACPI Tables 에 존재하는 `CpuPm` 테이블을 추가로 더 Drop 하여도 동일합니다...

아래의 사진에서 SSDT-2,3 과 같이 Clover 가 추가 및 수정한 CPU 관련 SSDT Tables 가 인젝션되었지만 Speed Step 이 작동하지 않습니다.

![스크린샷 2021-03-18 오후 4 02 34](https://user-images.githubusercontent.com/61459016/111587009-fbc26580-8804-11eb-9262-5efa7938ffad.png)

Speed Step 이 작동하지 않으면 아래의 증상이 나타납니다.
- 시스템이 1/2배로 느리게 작동합니다.
- 배터리 잔량 표시가 항상 0% 로 표시됩니다.
- 시스템 환경설정의 에너지 절약 설정에서 배터리 관련 설정이 보이지 않게 됩니다.

![스크린샷 2021-03-18 오후 4 01 26](https://user-images.githubusercontent.com/61459016/111587025-ffee8300-8804-11eb-951e-523deabc5fae.png)

전에 InsanelyMac 사이트에서 [이에 대한 글](https://www.insanelymac.com/forum/topic/346212-the-system-randomly-slows-down-after-booting-os-x-lion-1075-opencore-r064/)을 작성한 적이 있습니다.

Clover 로 부팅하여 Speed Step 이 작동하면 아래의 사진과 같이 표시됩니다.

![스크린샷 2021-03-18 오후 4 13 02](https://user-images.githubusercontent.com/61459016/111587079-10066280-8805-11eb-8131-3c223f1014e1.png)

**Comment by whatnameisit** [comment]
클로버와 오픈코어 ACPI 테이블이 완전히 같은데 오픈코어에서만 문제가 되나요? 그러면 클로버에서 1세대 CPU의 PM 관련한 커널패치를 적용하는 것 같습니다. 소스코드를 한 번 확인해봐야 할 것 같습니다.

**Comment by lshbluesky** [comment]
> 클로버와 오픈코어 ACPI 테이블이 완전히 같은데 오픈코어에서만 문제가 되나요? 그러면 클로버에서 1세대 CPU의 PM 관련한 커널패치를 적용하는 것 같습니다. 소스코드를 한 번 확인해봐야 할 것 같습니다.

네, Clover 와 OpenCore 의 ACPI 테이블이 완전히 같도록 OpenCore 에서 패치된 DSDT.aml 을 로드하고
Clover 가 추가 및 수정한 CPU 관련 SSDT Tables 도 로드하도록 하였지만 Speed Step 이 작동하지 않습니다... ㅜㅅㅠ

혹시나 해서 Kernel - Quirks 의 AppleCpuPmCfgLock 을 True 로 설정하고 다시 부팅해 보았지만 동일하네요...

당분간은 OpenCore 가 아닌 Clover 로 사용하려고 합니다.
그동안, 도움 주셔서 감사합니다. :)
죄송하게도, 제가 다음주 월요일부터 18개월동안 GitHub 와 X86 사이트등의 인터넷에 잘 접속하지 못할 수도 있습니다. (🇰🇷 R.O.K.A)

좋은 하루 보내세요. ✨
안녕히 계세요. :)

**Comment by whatnameisit** [comment]
안 되었다니 아쉽네요. ACPI가 클로버와 오픈코어에서 같다고 말씀해주셨지만 혹시 모르니 클로버에 있는 SSDT를 전부 저장해서 오픈코어에서 OEM SSDT를 드롭하고 클로버 SSDT를 순서대로 더해보면 작동할 수 있겠다는 생각이 듭니다. 이때도 작동하지 않는다면 확실히 커널 패치를 추가로 적용해야 하는 부분이겠죠.
먼 시간 동안 말로 다 할 수 없는 곳을 다녀오시는군요. 건강 잘 챙기시고 조금이라도 보람차셨으면 좋겠습니다. 잘 다녀오세요 :)

**Comment by lshbluesky** [comment]
안녕하세요. 🙂
오랜만에 인사드려요. :)
휴가를 나오고 거의 집에만 있어서 오랜만에 다시 OpenCore r0.7.1 버전으로 업데이트를 하였습니다.
그런데, 문제가 어느 정도 해결된 것 같아요. ✨

전원 어댑터를 연결하지 않고 Clover 가 추가 및 수정한 CPU 관련 SSDT Tables 를 로드하지 않고 부팅하여도
시스템이 1/2배로 느리게 작동하지 않고 배터리 잔량 표시도 정상적으로 작동합니다.

예전에 제가 InsanelyMac 에서 작성하였던 [질문글](https://www.insanelymac.com/forum/topic/346212-the-system-randomly-slows-down-after-booting-os-x-lion-1075-opencore-r064/?do=findComment&comment=2756227)에서는 VoodooPState.kext 와 PStateMemu.app 에 대한 내용의 답변이 달렸었습니다.

![스크린샷 2021-07-12 오후 1 16 15](https://user-images.githubusercontent.com/61459016/125231938-9a278900-e316-11eb-85e4-299ae42109dd.png)

위의 스크린샷 사진은 OpenCore IA32 r0.7.1 로 전원 어댑터를 연결하지 않고 Clover 가 추가 및 수정한 CPU 관련 SSDT Tables 를 로드하지 않으면서 OS X Lion 10.7.5 를 부팅한 후에 VoodooPState.kext 가 로드된 상태에서 PStateMemu.app 을 확인한 모습입니다.
또한, VoodooPState.kext 를 로드하지 않도록 하여도 시스템이 1/2배로 느리게 작동하지 않고 배터리 잔량 표시도 정상적으로 작동합니다.
Intel Merom Core 2 Duo T5600 CPU 의 Speed Step 이 정상적으로 작동하는 것 같아요...! 🙊

단, 시스템 환경설정의 에너지 절약 설정에서 배터리 관련 설정이 보이지 않는 것은 동일합니다. (그래도, 이 부분은 넘어가도 될 것 같아요.)

OpenCore 버전을 r0.6.7 에서 r0.7.1 버전으로 한 번에 새로 다시 구축하여 업데이트를 진행하였는데
과연 그 버전 사이에 OpenCore 에서 Intel 2nd Gen Sandy Bridge 이전 세대의 CPU 에 대한 C & P States Generation 과 관련하여 변경된 부분이 있는 것일까요?

그래도, 문제는 해결된 것 같아서 알려드리고자 Issue 에 Comment 를 작성하였습니다.
혹시, 또 다른 의견이 있으시다면 Comment 남겨주세요. :)

그럼, 좋은 하루 보내세요. ✨
안녕히 계세요. :)

**Comment by whatnameisit** [comment]
안녕하세요. 좋은 시간 보내고 계시겠네요^^
오픈코어는 구세대 CPU detection을 계속 추가하고 있습니다. Commit history 보면 종종 있지요. 그래서 시스템 속도가 정상적인 것 같습니다.
배터리는 VirtualSMC와 SMCBatteryManager가 32-bit에서 작동하면 잘 될 것 같습니다. 계속 지원 OS 제한이 낮아지고 있어요. Lilu와 VirtualSMC feature branch 보시면 Goldfish64가 32-bit 커널 지원 코드 추가하고 있네요.
더운데 몸조리 잘 하세요^^
